// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjeuhhlrgwipyaxtbacb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqZXVoaGxyZ3dpcHlheHRiYWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDYxNTksImV4cCI6MjA2NTYyMjE1OX0.UXbBYKZbWzYQIzcZ4ZNoHJ8afJQOVhRMVL-4AkgJ3jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);